# Nombre de la aplicacion
spring.application.name=RestauranteAruba
# Definir el puerto con el cual se accedera a la aplicacion
server.port=8090
# Url del proyecto
server.servlet.context-path=/aruba

spring.datasource.url=jdbc:mysql://aruba-db.cj2g204uw8uv.sa-east-1.rds.amazonaws.com:3306/aruba_db
spring.datasource.username=root
spring.datasource.password=

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# H ibernate solo valida que las entidades coincidan
spring.jpa.hibernate.ddl-auto=validate